Web/SparkSide.Web/Areas/Trainer/Controllers/ChallengesManagerController.cs
namespace SparkSide.Web.Areas.Trainer.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using SparkSide.Data.Models;
    using SparkSide.Services.Data.Contracts;
    using SparkSide.Services.Data.Models;
    using SparkSide.Web.ViewModels.Challenges;

    public class ChallengesManagerController : TrainersController
    {
        private readonly IChallengesService challengesService;
        private readonly IWebHostEnvironment environment;
        private readonly UserManager<ApplicationUser> userManager;

        public ChallengesManagerController(
            IChallengesService challengesService,
            IWebHostEnvironment environment,
            UserManager<ApplicationUser> userManager)
        {
            this.challengesService = challengesService;
            this.environment = environment;
            this.userManager = userManager;
        }

        // GET: ChallengesManagerController
        public ActionResult Index()
        {
            // return only current trainer's challenges
            string trainerId = this.userManager.GetUserId(this.User);
            ICollection<ChallengeDTO> trainerChallenges = this.challengesService.GetUserCreatedChallenges(trainerId);

            return this.View(trainerChallenges);
        }

        // GET: ChallengesManagerController/Create
        public ActionResult Create()
        {
            return this.View(new CreateChallengeInputModel());
        }

        // POST: ChallengesManagerController/Create
        [HttpPost]
        public async Task<IActionResult> Create(CreateChallengeInputModel input)
        {
            try
            {
                if (!this.ModelState.IsValid)
                {
                    return this.View();
                };

                string userId = this.userManager.GetUserId(this.User);

                int challengeId = await this.challengesService.CreateAsync(input, userId, $"{this.environment.WebRootPath}/images");

                return this.RedirectToAction("Details", "Challenges", new { area = "", id = challengeId });
            }
            catch
            {
                return this.View();
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            ChallengeDTO challenge = await this.challengesService.GetByIdAsync(id);

            if (challenge != null && !challenge.IsPublished)
            {
                EditChallengeInputModel inputModel = new EditChallengeInputModel(challenge);

                return this.View(inputModel);
            }
            else
            {
                return this.NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditChallengeInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            try
            {
                ChallengeDTO challenge = await this.challengesService.GetByIdAsync(id);

                if (challenge != null && !challenge.IsPublished)
                {
                    await this.challengesService.UpdateAsync(id, input);

                    return this.RedirectToAction("Details", "Challenges", new { area = "", id = id });
                }
                else
                {
                    return this.NotFound();
                }
            }
            catch
            {
                return this.View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Publish(int id)
        {
            try
            {
                await this.challengesService.PublishAsync(id);
                return this.RedirectToAction(nameof(this.Index));
            }
            catch
            {
                return this.NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await this.challengesService.DeleteByIdAsync(id);
                return this.RedirectToAction(nameof(this.Index));
            }
            catch
            {
                return this.NotFound();
            }
        }
    }
}

Web/SparkSide.Web/Controllers/Api/UserActionsController.cs
namespace SparkSide.Web.Controllers.Api
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using SparkSide.Data.Models;
    using SparkSide.Services.Data.Contracts;
    using SparkSide.Web.ViewModels.Challenges;
    using SparkSide.Web.ViewModels.Users;

    [Authorize]
    [ApiController]
    [Route("api/[controller]")]
    public class UserActionsController : ControllerBase
    {
        private readonly IUsersService usersService;
        private readonly IChallengesService challengesService;

        private readonly UserManager<ApplicationUser> userManager;

        public UserActionsController(
            IUsersService usersService,
            IChallengesService challengesService,
            UserManager<ApplicationUser> userManager)
        {
            this.usersService = usersService;
            this.userManager = userManager;
            this.challengesService = challengesService;
        }

        [HttpPost]
        [Route(nameof(Follow))]
        public async Task<IActionResult> Follow([FromBody] UserFollowInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.BadRequest();
            }

            string currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (currentUserId == model.UserId)
            {
                return this.BadRequest("You cannot follow yourself.");
            }

            await this.usersService.FollowAsync(currentUserId, model.UserId);
            return this.Ok();
        }

        [HttpPost]
        [Route(nameof(Unfollow))]
        public async Task<IActionResult> Unfollow([FromBody] UserFollowInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.BadRequest();
            }

            string currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (currentUserId == model.UserId)
            {
                return this.BadRequest("You cannot unfollow yourself.");
            }

            await this.usersService.UnfollowAsync(currentUserId, model.UserId);

            return this.Ok();
        }

        [HttpPost]
        [Route(nameof(SaveChallenge))]
        public async Task<IActionResult> SaveChallenge([FromBody] ChallengeIdInputModel input)
        {
            if (!ModelState.IsValid)
            {
                return this.BadRequest();
            }

            try
            {
                string userId = this.userManager.GetUserId(this.User);
                await this.challengesService.AddToSavedAsync(userId, input.ChallengeId);

                return this.Ok();
            }
            catch (Exception ex)
            {
                return this.BadRequest();
            }

        }


        [HttpPost]
        [Route(nameof(UnsaveChallenge))]
        public async Task<IActionResult> UnsaveChallenge([FromBody] ChallengeIdInputModel input)
        {

            if (!this.ModelState.IsValid)
            {
                return this.BadRequest();
            }

            try
            {
                string userId = this.userManager.GetUserId(this.User);
                await this.challengesService.RemoveFromSavedAsync(userId, input.ChallengeId);

                return this.Ok();
            }
            catch (Exception ex)
            {
                return this.BadRequest();
            }
        }

        [HttpPost]
        [Route(nameof(StartChallenge))]
        public async Task<IActionResult> StartChallenge([FromBody] ChallengeIdInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.BadRequest();
            }

            try
            {
                string userId = this.userManager.GetUserId(this.User);
                await this.challengesService.AddToStartedAsync(userId, input.ChallengeId);

                return this.Ok();
            }
            catch (Exception ex)
            {
                return this.BadRequest();
            }

        }


        [HttpPost]
        [Route(nameof(CancelChallenge))]
        public async Task<IActionResult> CancelChallenge([FromBody] ChallengeIdInputModel input)
        {

            if (!this.ModelState.IsValid)
            {
                return this.BadRequest();
            }

            try
            {
                string userId = this.userManager.GetUserId(this.User);
                await this.challengesService.RemoveFromStartedAsync(userId, input.ChallengeId);

                return this.Ok();
            }
            catch (Exception ex)
            {
                return this.BadRequest();
            }
        }
    }
}

Web/SparkSide.Web/Controllers/ChallengesController.cs
namespace SparkSide.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using SparkSide.Common;
    using SparkSide.Data.Models;
    using SparkSide.Services.Data.Contracts;
    using SparkSide.Services.Data.Models;
    using SparkSide.Services.DTOs;
    using SparkSide.Web.ViewModels.Challenges;

    public class ChallengesController : Controller
    {
        private readonly IChallengesService challengesService;
        private readonly UserManager<ApplicationUser> userManager;

        public ChallengesController(
            IChallengesService challengesService,
            UserManager<ApplicationUser> userManager)
        {
            this.challengesService = challengesService;
            this.userManager = userManager;
        }

        public IActionResult All()
        {
            return this.View();
        }

        [Authorize]
        public async Task<IActionResult> CancelChallenge(int id)
        {
            try
            {
                string userId = this.userManager.GetUserId(this.User);
                await this.challengesService.RemoveFromStartedAsync(userId, id);
                return this.RedirectToAction("Saved");
            }
            catch
            {
                return this.NotFound();
            }

        }

        [Authorize]
        public IActionResult Saved()
        {
            string userId = this.userManager.GetUserId(this.User);
            ICollection<ChallengeDTO> challenges = this.challengesService.GetUserSavedChallenges(userId);

            return this.View(challenges);
        }

        [Authorize]
        public IActionResult Started()
        {
            string userId = this.userManager.GetUserId(this.User);
            ICollection<ActiveChallengeDTO> challenges = this.challengesService.GetUserStartedChallengesStats(userId);

            return this.View(challenges);
        }

        public async Task<IActionResult> Details(int id)
        {
            ChallengeDetailsViewModel details = new ChallengeDetailsViewModel();
            details.Challenge = await this.challengesService.GetByIdAsync(id);

            if (details.Challenge == null)
            {
                return this.NotFound();
            }

            if (!details.Challenge.IsPublished && details.Challenge.Author.LoginName != this.User.Identity.Name)
            {
                return this.NotFound();
            }

            details.Challenge.Tasks = this.challengesService.GetChallengeTasks(id).Select(c => new ChallengeTaskDTO(c)).ToList();

            string userId = this.userManager.GetUserId(this.User);

            details.IsStartButtonDisabled = this.challengesService.IsChallengeStarted(userId, details.Challenge.Id);
            details.IsSaveButtonDisabled = this.challengesService.IsChallengeSaved(userId, details.Challenge.Id);

            return this.View(details);
        }
    }
}

Web/SparkSide.Web/Controllers/UsersController.cs
namespace SparkSide.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using SparkSide.Data.Models;
    using SparkSide.Services.Data.Contracts;
    using SparkSide.Services.Data.Models;
    using SparkSide.Web.ViewModels.Users;
    using SparkSide.Common;
    using Microsoft.AspNetCore.Hosting;

    public class UsersController : Controller
    {
        private readonly IUsersService usersService;
        private readonly IChallengesService challengesService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment environment;

        public UsersController(
            IUsersService usersService,
            IChallengesService challengesService,
            UserManager<ApplicationUser> userManager,
            IWebHostEnvironment environment)
        {
            this.usersService = usersService;
            this.userManager = userManager;
            this.challengesService = challengesService;
            this.environment = environment;
        }

        [Authorize]
        [Route("Users/Settings")]
        public async Task<IActionResult> Settings()
        {
            ApplicationUser user = await this.userManager.GetUserAsync(this.User);
            UserSettingsInputModel model = new UserSettingsInputModel(user);

            return this.View(model);
        }

        [Authorize]
        [HttpPost]
        [Route("Users/Settings")]
        public async Task<IActionResult> Settings(UserSettingsInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            string currentUserId = this.userManager.GetUserId(this.User);

            if (currentUserId != input.UserId)
            {
                return this.View();
            }

            try
            {
                await this.usersService.UpdateUserSettingsAsync(input, $"{this.environment.WebRootPath}/images");
                return this.RedirectToAction("AllChallenges", "Explore");
            }
            catch
            {
                return this.View();
            }
        }

        [Authorize]
        [Route("Users/{loginName}")]
        public async Task<IActionResult> Index(string loginName)
        {
            bool isCurrentUser = false;
            bool isFollowing = false;
            UserDTO targetUser = this.usersService.GetByLoginName(loginName);
            if (loginName.ToLower() == this.User.Identity.Name.ToLower())
            {
                isCurrentUser = true;
            }
            else
            {
                ApplicationUser currentUser = await this.userManager.GetUserAsync(this.User);
                isFollowing = this.usersService.IsFollowing(currentUser.Id, targetUser.Id);
            }

            if (targetUser.ProfilePictureLink == string.Empty)
            {
                targetUser.ProfilePictureLink = "../img/" + GlobalConstants.DefaultProfilePictureName;
            }

            UserProfileViewModel model = new UserProfileViewModel();
            model.User = targetUser;
            model.IsCurrentUser = isCurrentUser;
            model.IsFollowing = isFollowing;
            model.IsTrainer = await this.usersService.IsInRoleAsync(targetUser.Id, GlobalConstants.TrainerRoleName);
            model.IsAdmin = await this.usersService.IsInRoleAsync(targetUser.Id, GlobalConstants.AdministratorRoleName);
            model.Challenges = this.challengesService.GetUserStartedChallenges(targetUser.Id);

            if (model.IsTrainer)
            {
                model.Challenges = this.challengesService.GetUserCreatedChallenges(targetUser.Id);
            }

            return this.View(model);
        }
    }
}

Web/SparkSide.Web/Views/Challenges/Details.cshtml
@using SparkSide.Common
@model SparkSide.Web.ViewModels.Challenges.ChallengeDetailsViewModel

@{
    this.ViewData["Title"] = Model.Challenge.Title;
}

<div>
    <div class="page-title">
        <h3>Details</h3>
    </div>
</div>

<center>
    <div class="mdl-card content-container challenge-container mdl-shadow--2dp ">
        <div class="title-container">
            <h3>@Model.Challenge.Title</h3>
        </div>
        <div class="action-buttons-container">
            @if (this.User.Identity.IsAuthenticated)
            {
                <div class="action-buttons">
                    @if (this.User.Identity.Name == Model.Challenge.Author.LoginName && !Model.Challenge.IsPublished)
                    {
                        <a class="edit-icon mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--primary"
                           asp-area="Trainer" asp-controller="ChallengesManager" asp-action="Edit" asp-route-id="@Model.Challenge.Id">
                            <i class="material-icons">edit</i>
                        </a>
                    }
                    else
                    {
                        <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent"
                                disabled="@Model.IsStartButtonDisabled" id="btnStart">
                            Start
                        </button>
                        <button disabled="@Model.IsSaveButtonDisabled" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored"
                                id="btnSave">
                            Save
                        </button>
                    }
                </div>
            }
        </div>
        <div class="author-container">
            by <a asp-controller="Users" asp-action="@Model.Challenge.Author.LoginName">@Model.Challenge.Author.FirstName @Model.Challenge.Author.LastName</a>
        </div>
        <div class="info">
            <div class="picture-container">
                <img class="challenge-picture" asp-append-version="true" src="@Model.Challenge.PictureLink" />
            </div>
            <div class="challenge-info-container">
                <div>
                    <strong>@Model.Challenge.DurationDays Days</strong>
                </div>
                <br />
                <div>
                    <p>@Model.Challenge.Description</p>
                </div>
            </div>
        </div>
        <div>
            @for (int i = 1; i <= Model.Challenge.DurationDays; i++)
            {
                <div id="Day-@i" class="challenge-task-card mdl-card mdl-shadow--2dp">
                    <div class="mdl-card__title">
                        <center><h2 class="mdl-card__title-text">Day @i</h2></center>
                    </div>
                    <ul id="tasksDay-@i" class="mdl-list">
                        @foreach (var task in Model.Challenge.Tasks.Where(t => t.Day == i))
                        {
                        <li class="mdl-list__item">
                            <span class="mdl-list__item-primary-content">
                                @task.Title
                            </span>
                        </li>
                        }
                    </ul>
                </div>
            }
        </div>
        <div>
            @foreach (var tag in Model.Challenge.Tags)
            {
                <span class="tag-chip-container mdl-chip">
                    <span class="mdl-chip__text">@tag</span>
                </span>
            }
        </div>
        <!--if (Model.Challenge.IsPublished)
        {
            <div>
                <div class="border-bottom">
                    <h4>Comments (3)</h4>
                </div>
                <br />-->
        @*comments*@
        <!--</div>
        }-->
        <br />
    </div>
</center>

@section Scripts {
<partial name="_SaveAndStartScriptsPartial" for="@Model.Challenge" />
}

Web/SparkSide.Web/Views/Challenges/Followed.cshtml
@model ICollection<SparkSide.Services.DTOs.ActiveChallengeDTO>

@{
    this.ViewData["Title"] = "Started Challenges";
}

<div>
    <div class="page-title">
        <h3>@ViewData["Title"]</h3>
    </div>
</div>

<div class="content-container">
    @if (Model.Count == 0)
    {
        <div>No challenges started.</div>
    }
    else
    {
        <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
            <thead>
                <tr>
                    <th class="mdl-data-table__cell--non-numeric">Title</th>
                    <th class="mdl-data-table__cell--non-numeric">Progress</th>
                    <th class="mdl-data-table__cell--non-numeric">Started On</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var challenge in Model)
                {
                    <tr>
                        <td class="mdl-data-table__cell--non-numeric">@challenge.Title</td>
                        <td>@challenge.Progress %</td>
                        <td class="mdl-data-table__cell--non-numeric">@challenge.StartedOn</td>
                        <td>
                            <a class="mdl-button mdl-js-button mdl-button--primary"
                               asp-area="" asp-controller="Challenges" asp-action="Details" asp-route-id="@challenge.Id">
                                Details
                            </a>
                            <span>|</span>
                            <form class="form-button" method="post">
                                <button type="submit" class="mdl-button mdl-js-button mdl-button--primary"
                                        asp-area="" asp-controller="Challenges" asp-action="CancelChallenge" asp-route-id="@challenge.Id">
                                    Remove
                                </button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

Web/SparkSide.Web/Views/Challenges/Saved.cshtml
@model IEnumerable<SparkSide.Services.Data.Models.ChallengeDTO>

@{
    this.ViewData["Title"] = "Saved Challenges";
}

<div>
    <div class="page-title">
        <h3>@ViewData["Title"]</h3>
    </div>
</div>

<div class="card-results-container">
    @foreach (var challenge in Model)
    {
        <div id="Challenge-@challenge.Id" class="challenge-display-container">
                <form class="action-button" method="post">
                    <button id="btnUnsave" onclick="remove(@challenge.Id)" class="mdl-button mdl-js-button mdl-button--icon" type="submit">
                        <i class="material-icons action-icon">delete</i>
                    </button>
                </form>
            <div class="partial-challenge-container">
                <partial name="~/Views/Shared/_ChallengeCardDisplayPartial.cshtml" for="@challenge" />
            </div>
        </div>
    }
</div>

@section Scripts {
    <script>
        function remove(challengeId) {
         var unsaveButton  = $("#btnUnsave");
            unsaveButton.attr("disabled", true);
            $.ajax({
                method: "POST",
                url: '@Url.Action("UnsaveChallenge", "UserActions")',
                data: JSON.stringify({
                    'ChallengeId': challengeId,
                }),
                contentType: "application/json",
                success: function () {
                    $("#Challenge-" + challengeId).remove();
                },
                error: function () {
                    alert("Error removing challenge");
                    unsaveButton.attr("disabled", false);
                }
            });
            return false;
        }
    </script>
}

Web/SparkSide.Web/Views/Challenges/Started.cshtml
@model ICollection<SparkSide.Services.DTOs.ActiveChallengeDTO>

@{
    this.ViewData["Title"] = "Started Challenges";
}

<div>
    <div class="page-title">
        <h3>@ViewData["Title"]</h3>
    </div>
</div>

<div class="content-container">
    @if (Model.Count == 0)
    {
        <div>No challenges started.</div>
    }
    else
    {
        <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
            <thead>
                <tr>
                    <th class="mdl-data-table__cell--non-numeric">Title</th>
                    <th class="mdl-data-table__cell--non-numeric">Progress</th>
                    <th class="mdl-data-table__cell--non-numeric">Started On</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var challenge in Model)
                {
                    <tr>
                        <td class="mdl-data-table__cell--non-numeric">@challenge.Title</td>
                        <td>@challenge.Progress %</td>
                        <td class="mdl-data-table__cell--non-numeric">@challenge.StartedOn</td>
                        <td>
                            <a class="mdl-button mdl-js-button mdl-button--primary"
                               asp-area="" asp-controller="Challenges" asp-action="Details" asp-route-id="@challenge.Id">
                                Details
                            </a>
                            <span>|</span>
                            <form class="form-button" method="post">
                                <button type="submit" class="mdl-button mdl-js-button mdl-button--primary"
                                        asp-area="" asp-controller="Challenges" asp-action="CancelChallenge" asp-route-id="@challenge.Id">
                                    Remove
                                </button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

Web/SparkSide.Web/Views/Challenges/_CommentPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Web/SparkSide.Web/Views/Challenges/_SaveAndStartScriptsPartial.cshtml
@model SparkSide.Services.Data.Models.ChallengeDTO

<script type="text/javascript">
    $(() => {
        var startButton = $("#btnStart");
        startButton.click(() => {
            startButton.attr("disabled", true);
            $.ajax({
                method: "POST",
                url: '@Url.Action("StartChallenge", "UserActions")',
                data: JSON.stringify({
                    'ChallengeId': '@Model.Id',
                }),
                contentType: "application/json",
                success: function () {
                    startButton.text("Started");
                },
                error: function () {
                    alert("Error starting challenge.");
                    startButton.attr("disabled", false);
                }
            });
            return false;
        });

        var saveButton  = $("#btnSave");
        saveButton.click(() => {
            saveButton.attr("disabled", true);
            $.ajax({
                method: "POST",
                url: '@Url.Action("SaveChallenge", "UserActions")',
                data: JSON.stringify({
                    'ChallengeId': '@Model.Id',
                }),
                contentType: "application/json",
                success: function () {
                    saveButton.text("Saved");
                },
                error: function () {
                    alert("Error saving challenge");
                    saveButton.attr("disabled", false);
                }
            });
            return false;
        });
    });

</script>  